name: fauto

services:
  bun:
    container_name: fauto-bot
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: bun production
    volumes:
      - .:/app
      - /app/node_modules
